# services.py

from models import User, Provider, Category, Product, Service

class DonationSystem:
    def __init__(self):
        self.users: list[User] = [] # List to store users
        self.providers: list[Provider] = [] # List to store providers
        self.categories: list[Category] = [] # List to store categories
        self.products: list[Product] = [] # List to store products
        self.services: list[Service] = [] # List to store services

        self._next_user_id = 1 # Internal counter for user IDs
        self._next_provider_id = 1 # Internal counter for provider IDs
        self._next_category_id = 1 # Internal counter for category IDs
        self._next_product_id = 1 # Internal counter for product IDs
        self._next_service_id = 1 # Internal counter for service IDs
        self._seed_demo_data()

    def _seed_demo_data(self) -> None:
        """Δημιουργούμε 3 κατηγορίες για τις δοκιμές των προϊόντων."""
        # Προϊόντα
        self.add_category("Οικιακή Συσκευή", "product")
        self.add_category("Ρούχο", "product")
        self.add_category("Έπιπλο", "product")
        
        """Δημιουργούμε 2 κατηγορίες για τις δοκιμές των υπηρεσιών."""
        # Υπηρεσίες
        self.add_category("Τεχνική Εργασία", "service")
        self.add_category("Ιατρική Βοήθεια", "service") 
            
 # ---Categories ---


    def add_category(self,category_name: str, category_type: str) -> Category:
        category = Category(self._next_category_id, category_name, category_type)
        self.categories.append(category) # Add category to the list
        self._next_category_id += 1 # Increment category ID for next category (if it becomes necessary)
        return category

    def list_categories(self) -> list[Category]:
        return self.categories # Return the list of categories
    
    def get_product_categories(self) -> list[Category]:
        """Επιστρέφει μόνο τις κατηγορίες προϊόντων."""
        results = []  # Create empty list
        for c in self.categories:
            if c.category_type == "product": 
                results.append(c)  # Add it to the list
        return results
           
          
    def get_service_categories(self) -> list[Category]:
        """Επιστρέφει μόνο τις κατηγορίες υπηρεσιών."""
        results = []  # Create empty list
        for c in self.categories:
            if c.category_type == "service": 
                results.append(c)  # Add it to the list
        return results
        

    def find_category_by_id(self, category_id: int) -> Category | None:
        for c in self.categories:
            if c.category_id == category_id: # category found
                return c # Return the category
        return None # No match found 
    

    # --- Users ---

    def create_user_session(self, username: str, full_name: str, phone: int, email: str, afm: int) -> User:
        user = User(                   # For the User
        user_id   =self._next_user_id, # Auto-incremented ID generated by the system
        username=username,             # The username provided during Login
        password="***",                # Security: Password already verified through login phase we don't store it here
        full_name=full_name,           # Real name collected during identification
        phone=phone,                   # Contact number collected during identification
        email=email,                   # Email address collected during identification
        AFM=afm,                       # Tax ID used for unique citizen identification
        total_points=0                 # Initialization: All new sessions start with 0 points
    )
        self.users.append(user)        # Add the new user to the system's list
        self._next_user_id += 1        # Increment ID for the next user
        return user
    
    # --- Providers ---

    def create_provider_session(self, username: str, full_name: str, phone: int, email: str, afm: int) -> Provider:
        provider = Provider(                     # For the Provider
            provider_id=self._next_provider_id,  # Auto-incremented ID generated by the system
            username=username,                   # The username provided during Login
            password="***",                      # Security: Password already verified through login phase we don't store it here
            full_name=full_name,                 # Real name collected during identification
            phone=phone,                         # Contact number collected during identification
            email=email,                         # Email address collected during identification
            AFM=afm                              # Tax ID used for unique citizen identification
        )
        self.providers.append(provider)          # Add the new provider to the system's list
        self._next_provider_id += 1              # Increment ID for the next provider
        return provider
    
     # --- Products ---

    def register_product(self, user: User, category_id: int, prod_name: str, 
                         prod_brand: str, purchase_year: int, usage_years: int, 
                         prod_photo: str) -> Product | None:
        
        #  Check Category
        category = self.find_category_by_id(category_id)
        if category is None: 
            print("Δεν βρέθηκε κατηγορία με αυτό το id.") 
            return None 
        
        if category.category_type != "product":
            print("Σφάλμα: Επιλέξατε κατηγορία υπηρεσίας αντί για προϊόν.")
            return None

        #  Create Product
        product = Product(
            product_id=self._next_product_id, # Auto-increment ID generated by the system
            prod_name=prod_name,              # Input provided by the user
            prod_brand=prod_brand,
            purchase_year=purchase_year,
            usage_years=usage_years,
            prod_photo=prod_photo,
            category=category,                # Connects the product to its Category
            user=user                         # Connects the product to its User
        )
        if product.check_availability():      # The product is added to the list only if it is valid.
            self.products.append(product)     # Saves the product to the system's memory list
            self._next_product_id += 1        # Increment ID for the next product
            user.add_points()                 # Adds points to the donor's profile
            return product
        else:
            return None

    def get_user_products(self, user: User) -> list[Product]:
        """Επιστρέφει τα προϊόντα του συγκεκριμένου χρήστη."""
        results = []  # Create empty list
        for p in self.products:
            if p.user == user: 
                results.append(p)  # Add it to the list
        return results
        
        
    # --- Services ---

    def register_service(self, provider: Provider, category_id: int, service_name: str, 
                         description: str, available_time: str) -> Service | None:
        
        category = self.find_category_by_id(category_id)
        if category is None:
            print("Δεν βρέθηκε κατηγορία με αυτό το id.")
            return None
        
        if category.category_type != "service":
            print("Σφάλμα: Επιλέξατε κατηγορία προϊόντος αντί για υπηρεσία.")
            return None

        # Create Service
        service = Service(
            service_id=self._next_service_id, # Auto-increment ID generated by the system
            service_name=service_name,        # Input provided by the provider
            service_description=description,
            available_time=available_time,
            category=category,                # Connects the service to its Category
            provider=provider                 # Connects the service to the Provider offering it
        )

        if service.check_availability():      # The service is added to the list only if it is valid.
            self.services.append(service)     # Saves the service to the system's memory list
            self._next_service_id += 1        # Increment ID for the next service
            return service
        else:
            return None   
    
    def get_provider_services(self, provider: Provider) -> list[Service]:
        """Επιστρέφει τις υπηρεσίες του συγκεκριμένου παρόχου."""
        results = []  # Create empty list
        for s in self.services:
            if s.provider == provider: 
                results.append(s)  # Add it to the list
        return results
    